
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Label numero1;
	
	private global::Gtk.Entry num1;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label numero2;
	
	private global::Gtk.Entry num2;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Button buttonSuma;
	
	private global::Gtk.Button buttonresta;
	
	private global::Gtk.Button buttonmultiplicacion;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label sumares;
	
	private global::Gtk.Label resultadoop;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label restares1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label multires1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.numero1 = new global::Gtk.Label ();
		this.numero1.Name = "numero1";
		this.numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Primer Número");
		this.vbox5.Add (this.numero1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.numero1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.num1 = new global::Gtk.Entry ();
		this.num1.CanFocus = true;
		this.num1.Name = "num1";
		this.num1.Text = global::Mono.Unix.Catalog.GetString ("Introduce un número");
		this.num1.IsEditable = true;
		this.num1.InvisibleChar = '•';
		this.vbox5.Add (this.num1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.num1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox5]));
		w3.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.numero2 = new global::Gtk.Label ();
		this.numero2.Name = "numero2";
		this.numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Segundo Número");
		this.vbox6.Add (this.numero2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.numero2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.num2 = new global::Gtk.Entry ();
		this.num2.CanFocus = true;
		this.num2.Name = "num2";
		this.num2.Text = global::Mono.Unix.Catalog.GetString ("Introduce un número");
		this.num2.IsEditable = true;
		this.num2.InvisibleChar = '•';
		this.vbox6.Add (this.num2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.num2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox6]));
		w6.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		this.vbox1.Add (this.vbox7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox7]));
		w7.Position = 2;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.buttonSuma = new global::Gtk.Button ();
		this.buttonSuma.CanFocus = true;
		this.buttonSuma.Name = "buttonSuma";
		this.buttonSuma.UseUnderline = true;
		this.buttonSuma.Label = global::Mono.Unix.Catalog.GetString ("Suma");
		this.vbox2.Add (this.buttonSuma);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonSuma]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.buttonresta = new global::Gtk.Button ();
		this.buttonresta.CanFocus = true;
		this.buttonresta.Name = "buttonresta";
		this.buttonresta.UseUnderline = true;
		this.buttonresta.Label = global::Mono.Unix.Catalog.GetString ("Resta");
		this.vbox2.Add (this.buttonresta);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonresta]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.buttonmultiplicacion = new global::Gtk.Button ();
		this.buttonmultiplicacion.CanFocus = true;
		this.buttonmultiplicacion.Name = "buttonmultiplicacion";
		this.buttonmultiplicacion.UseUnderline = true;
		this.buttonmultiplicacion.Label = global::Mono.Unix.Catalog.GetString ("Multiplicación");
		this.vbox2.Add (this.buttonmultiplicacion);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonmultiplicacion]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.sumares = new global::Gtk.Label ();
		this.sumares.Name = "sumares";
		this.sumares.LabelProp = global::Mono.Unix.Catalog.GetString ("=");
		this.hbox2.Add (this.sumares);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.sumares]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.resultadoop = new global::Gtk.Label ();
		this.resultadoop.Name = "resultadoop";
		this.hbox2.Add (this.resultadoop);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.resultadoop]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.restares1 = new global::Gtk.Label ();
		this.restares1.Name = "restares1";
		this.hbox3.Add (this.restares1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.restares1]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.multires1 = new global::Gtk.Label ();
		this.multires1.Name = "multires1";
		this.hbox4.Add (this.multires1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.multires1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w20.Position = 2;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 378;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
